# Generated by Django 5.2.16 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_confirmation", "بانتظار التأكيد"),
                    ("new", "جديد"),
                    ("confirmed", "تم التأكيد"),
                    ("preparing", "جاري التجهيز"),
                    ("shipped", "تم الشحن"),
                    ("delivered", "تم التسليم"),
                    ("cancelled", "ملغي"),
                    ("returned", "مرتجع"),
                ],
                default="new",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="confirmation_method",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="whatsapp_confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WhatsAppWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_name", models.CharField(blank=True, max_length=80)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-received_at"]},
        ),
    ]
