# Generated by Django 5.2.16 on 2026-08-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('subject', models.CharField(max_length=180, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'جارٍ المتابعة'), ('closed', 'مغلقة')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_tagline', models.CharField(default='تصميم هادئ. حضور لا يُنسى.', max_length=180, verbose_name='وصف العلامة')),
                ('announcement_text', models.CharField(blank=True, max_length=180, verbose_name='شريط الإعلان')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الدعم')),
                ('support_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف الدعم')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='رابط WhatsApp')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط Instagram')),
                ('business_hours', models.CharField(blank=True, max_length=180, verbose_name='ساعات العمل')),
                ('standard_shipping', models.DecimalField(decimal_places=2, default=70, max_digits=8, verbose_name='الشحن القياسي')),
                ('express_shipping', models.DecimalField(decimal_places=2, default=120, max_digits=8, verbose_name='الشحن السريع')),
                ('returns_days', models.PositiveSmallIntegerField(default=14, verbose_name='مدة الاسترجاع بالأيام')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
    ]
